# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JbM7cG-0QtzmUpU_PIhor7XUDJG9faux
"""

n = int(input())
print = (n * 2)

if False:
  print("1")
elif True:
  print("2")
elif True:
  print("3")
else:
  print("4")